version: "3.6"

services:
  ui:
    container_name: album_gallery
    stdin_open: true
    build:
      context: UI
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/src
    ports:
      - "3000:3000"
