export const UPDATE_ALBUM_LIST = "UPDATE_ALBUM_LIST";
export const UPDATE_USER_LIST = "UPDATE_USER_LIST";
export const UPDATE_PHOTO_LIST = "UPDATE_PHOTO_LIST";
export const UPDATE_PAGE_LIMIT = "UPDATE_PAGE_LIMIT";
export const USER_ID = 'USER_ID'
